name: Build obsidian plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: git config --global url."git@github.com:".insteadOf https://github.com/
      - run: git config --global url."git://".insteadOf https://
      - run: npm ci
      - run: npm run build --if-present
      - run: zip -r obsidian_local_images_plus_latest.zip ./obsidian_local_images_plus_latest
      - run: ls ./obsidian_local_images_plus_latest
      - run:  echo "::set-output name=tag_name::$(git tag --sort version:refname | tail -n 1)"



