name: Build obsidian plugin

on:
    push:
        tags:
            - "*"

env:
    PLUGIN_NAME: obsidian-local-images-plus

jobs:
    release:
        runs-on: ubuntu-latest 
        steps:
        - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

*******************************************************************************

        - name: Reconfigure git to use HTTP authentication
         run:
                  git config --global url."git@github.com:".insteadOf https://github.com/
                  git config --global url."git://".insteadOf https://

*******************************************************************************
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: "16.x"
            - name: Build
              id: build
              run:                
                  npm ci
                  npm run build 
                  mkdir obsidian_local_images_plus_latest
                  cp main.js manifest.json styles.css obsidian_local_images_plus_latest

                  zip -r obsidian_local_images_plus_latest.zip obsidian_local_images_plus_latest
                  ls
                  echo "::set-output name=tag_name::$(git tag --sort version:refname | tail -n 1)"
            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  VERSION: ${{ github.ref }}
              with:
                  tag_name: ${{ github.ref }}
                  release_name: ${{ github.ref }}
                  draft: false
                  prerelease: false
            - name: Upload zip file
              id: upload-zip
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./obsidian_local_images_plus_latest.zip
                  asset_name: obsidian_local_images_plus_latest-${{ steps.build.outputs.tag_name }}.zip
                  asset_content_type: application/zip
            - name: Upload main.js
              id: upload-main
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./main.js
                  asset_name: main.js
                  asset_content_type: text/javascript
            - name: Upload manifest.json
              id: upload-manifest
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./manifest.json
                  asset_name: manifest.json
                  asset_content_type: application/json
